### PR TITLE
Removed Invulnerable to allow EntityDamageByEntityEvent to be triggered

### PR DESCRIPTION
**Pull request by Xemorr**
Removed Invulnerable to allow EntityDamageByEntityEvent to be triggered
This improves bedrock support and allows them to actually redeem graves.
I have also changed the config to cache values as if you decompile all of those get methods in the config class, it's a lot more inefficient than a getter should be.

This change may have unforeseen consequences but I'm not sure what they are yet, with regards to graves being broken in weird circumstances.

### CODE REVIEW

**Comment by orang3-juic3** [comment]
Does removing Invulnerable mean that the armor stand could possibly be exploded?

**Review by orang3-juic3 — CHANGES_REQUESTED** [review]
A function call for 'reloadWorldList' is unnecessary, should be inlined to just config..getStringList("worlds")

**Comment by orang3-juic3** [comment]
I support the idea of using an enum rather than an int for itemReturnMode here https://github.com/CoolDCB/DavesGraves/pull/3/commits/cee50b61ffe02ded5819facf50373644199945c5
I would be more than happy to implement that if this gets merged.

**Review by orang3-juic3 — CHANGES_REQUESTED** [review]
Nothing is done apart from setting the armor stand to Invulnerable in PlayerEvents.java.
PlayerInteractEntityEvent is imported but not used.

**Comment by Xemorr** [comment]
> 
> 
> Does removing Invulnerable mean that the armor stand could possibly be exploded?

This shouldn't happen as all sources of explosions are from entities technically. I think it's more likely for there to be silly things like a cactus breaking an armor stand.

**Comment by Xemorr** [comment]
> 
> 
> A function call for 'reloadWorldList' is unnecessary, should be inlined to just config..getStringList("worlds")

I didn't change that, that was Dave who did that, and I support it personally

**Comment by Xemorr** [comment]
Another thing to note, is this change renders the sneaking to break graves redundant, of course that can be left but something to consider if you want to remove any technical debt

**Comment by orang3-juic3** [comment]
Makes sense. I approve this change now, up to dave to merge

**Pull request closed without merging**
